# loads all the properties of application.properties,
# if any property is same, the property in this file overrides that property.

my.property.name2 = Hello from "application.properties" of PROD environment...