spring.application.name = demo
#spring.profiles.active = dev, test, prod
# active profile can also be set programatically as see in main file DemoApplication.java, but priority is given to this file if defined in this
# last given profile will be activated as it overrides each one by one...

my.property.name1 = Hello from "application.properties" file thru Environment...

my.property.name2 = Hello from "application.properties" file

my.prop.num = 1939